version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python_app
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
